name: Check diff contents per jobs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add new file
        run: |
          echo new > hello.txt

      - name: List files
        run: |
          ls -la

  job2:
    runs-on: ubuntu-latest

    needs:
      - job1

    steps:
      - name: List files
        run: |
          ls -la
