name: Copilot Review Enforcer

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  copilot_review_enforcer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Run Copilot Review Enforcer
        uses: book000/copilot-review-enforcer@v1.0.2
