name: Copilot Review Enforcer

on:
  pull_request:
    types: [opened, reopened]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  copilot_review_enforcer:
    runs-on: ubuntu-latest
    steps:
      - name: Run Copilot Review Enforcer
        uses: book000/copilot-review-enforcer@v1.1.5
