name: Example WireGuard SSH Usage

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute on remote server'
        required: false
        default: 'hostname && whoami && pwd && uptime'
        type: string

jobs:
  wireguard-ssh-example:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect via WireGuard and execute SSH command
        uses: ./
        with:
          command: ${{ github.event.inputs.command }}
          wireguard-private-key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          wireguard-address: ${{ secrets.WIREGUARD_ADDRESS }}
          wireguard-dns: ${{ secrets.WIREGUARD_DNS || '1.1.1.1' }}
          wireguard-peer-public-key: ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }}
          wireguard-preshared-key: ${{ secrets.WIREGUARD_PRESHARED_KEY }}
          wireguard-endpoint: ${{ secrets.WIREGUARD_ENDPOINT }}
          wireguard-allowed-ips: ${{ secrets.WIREGUARD_ALLOWED_IPS }}
          ssh-private-key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          ssh-user: ${{ secrets.HOME_SERVER_USER }}
          ssh-hostname: ${{ secrets.HOME_SERVER_HOSTNAME }}
          ssh-host-ip: ${{ secrets.HOME_SERVER_IP }}
          ssh-host-key: ${{ secrets.HOME_SERVER_HOST_KEY }}
          ssh-port: '22'