name: Code Formatter with book000/starbound-jsonc-formatter

on: [ pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: 

      - name: Run book000/starbound-jsonc-formatter
        uses: book000/starbound-jsonc-formatter@master
        
      - name: check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Set git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config pull.rebase true

      - name: push changes
        id: push-changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "fix: apply jsonc format"
