name: Check sharing jobs apt

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install libasound2-dev
        run: |
          apt install -y libasound2-dev
  job2:
    runs-on: ubuntu-latest

    needs:
      - job1

    steps:
      - name: Install libasound2-dev
        run: |
          apt install -y libasound2-dev
