name: Sync develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop

      - name: Sync develop (rebase)
        id: sync-rebase
        run: |
          git fetch --all
          git rebase main develop
          if git push origin develop; then
            echo "::set-output name=result::true"
          else
            echo "::set-output name=result::false"
          fi

      - name: Sync develop (merge)
        if: steps.sync-rebase.outputs.result == 'false'
        run: |
          git merge main
          git push origin develop
